### ISSUE TITLE
HDMI输出4k

### ISSUE THREAD

**Issue by SwaggyZhang** [coressss/Hackintosh-LENOVO-xiaoxin700-ideapad700-Opencore-OC#3]
您好，我的小新700没法使用HDMI输出4K，按网上的方法更改framebuffer-stolenmem之后会无法开机，请问您的电脑可以输出4K吗？

**Comment by coressss** [comment]
你好，我这也不能输出4k，单HD530核显就算能输出4k性能就可想而知了。我觉得没必要纠结这个问题。

2022年10月16日 19:49，SwaggyZhang ***@***.***> 写道：



您好，我的小新700没法使用HDMI输出4K，按网上的方法更改framebuffer-stolenmem之后会无法开机，请问您的电脑可以输出4K吗？

**Comment by SwaggyZhang** [comment]
13寸的白果也是核显，不知它输出4K的效果怎么样，所以想试一下，就算是4K 30Hz也无所谓~

谢谢！
